### ISSUE TITLE
Xcode Build Failure After Install With Carthage

### ISSUE THREAD

**Issue by cabenso** [JanC/XPConnectKit#1]
I'm working on an aviation related iOS app and would like to do some testing with X Plane.  The XPConnectKit looks like a great way to do this.  
On two different projects I've tried to install the XPConnectKit with Carthage and get a build failure in Xcode after doing so.  Specifically, "Command PhaseScriptExecution failed with a nonzero exit code".  I have little experience with Swift and Xcode, so there is a good chance this is user error.  Should there be a XPConnectKit.framework file in the Build/iOS folder?  Currently there's only CocoaAsyncSocket.framework and XPDiscoverKit.framework.
I appreciate any help!  Using Xcode 10.0 and Carthage 0.33.0.
![Image 5-27-19 at 5 40 PM](https://user-images.githubusercontent.com/41840302/58440414-def4f500-80a7-11e9-9f4c-7ede94178a47.jpg)
![Image 5-26-19 at 1 45 PM](https://user-images.githubusercontent.com/41840302/58440416-e0beb880-80a7-11e9-8144-49dff5233869.jpg)

**Comment by JanC** [comment]
Hi @cabenso 

there was indeed a problem and the `XPConnectKit` was no building in Carthage. I fixed it and it should work now in the `master` branch. Can you make sure that you have the `mater` branch specified in your `Cartfile`:

```
github "JanC/XPConnectKit" "master"
```

Then run `carthage update`. You should now see those frameworks in Carthage the build folder:

```
CocoaAsyncSocket.framework
XPConnectKit.framework
XPDiscoveryKit.framework
```
You can then drag and drop them all in the `Embedded Binaries` phase of your main app's General build setting tab

<img width="699" alt="Screenshot 2019-05-28 at 07 04 41" src="https://user-images.githubusercontent.com/707703/58452212-e56e8580-8116-11e9-98db-4db1c44d6d6f.png">

**Comment by cabenso** [comment]
Hey @JanC, it works now! Thanks for the help.
